### ISSUE TITLE
Deleting nested structures using InnoDb

### ISSUE THREAD

**Issue by taat** [blt04/doctrine2-nestedset#14]
Looks like there's a bug, when deleting nested structures when using InnoDb.

The problem is described here:

http://stackoverflow.com/questions/7048991/doctrine-2-tree-nestedset-and-innodb

For sqlite the same schema works ok. Any ideas how to fix this?

**Comment by blt04** [comment]
Did you mean to post this on this project: https://github.com/l3pp4rd/DoctrineExtensions

**Comment by taat** [comment]
Ah, yes. I'm sorry for this :)
