### ISSUE TITLE
If fetchTree gets called multiple times, duplicate items show up in the return value

### ISSUE THREAD

**Issue by Drachenkaetzchen** [blt04/doctrine2-nestedset#2]
Reproduce code:

$mg = new Manager($config);
$mg->fetchTree(1);
$mg->fetchTree(1);

The result from the second fetchTree contains now duplicate items.

**Comment by aweiland** [comment]
I noticed this too.  I made a quick fix in my fork.  Not sure if it's the best way or not

SHA: ae2ecf2a8f4a2f0965c567afcb1c564c5356ae70

**Comment by blt04** [comment]
Thanks for the bug report!  This should be fixed in 8dd224c19246ee786f8750bddef10f3925815b18

aweiland, thank you for your fix.  It did work however I am completely rebuilding the tree just in case.

**Comment by Drachenkaetzchen** [comment]
Great work, will try it out later!

**Comment by aweiland** [comment]
Seems to be working well.  Thanks!
